
export WALLAROO_HOST_PREFIX=127.0.0
export WALLAROO_INIT_HOST=${WALLAROO_HOST_PREFIX}.1
# workers have host IP addresses of ${WALLAROO_HOST_PREFIX}.{worker#}

export WALLAROO_OUT_HOST=$WALLAROO_INIT_HOST
export WALLAROO_METRICS_HOST=$WALLAROO_INIT_HOST

export WALLAROO_IN_PORT=7100
export WALLAROO_CONTROL_PORT=7101
export WALLAROO_DATA_PORT=7102
export WALLAROO_EXTERNAL_PORT=7103
export WALLAROO_MY_CONTROL_PORT=7104
export WALLAROO_MY_DATA_PORT=7105

export WALLAROO_BIN="./examples/pony/aloc_passthrough/aloc_passthrough"
export WALLAROO_ARG_IN="InputBlobs@${WALLAROO_INIT_HOST}:${WALLAROO_IN_PORT}:Dragons-Love-Tacos:500:50"
export WALLAROO_ARG_OUT="${WALLAROO_OUT_HOST}:7200"
export WALLAROO_ARG_METRICS="${WALLAROO_METRICS_HOST}:5001"
export WALLAROO_ARG_CONTROL="${WALLAROO_INIT_HOST}:${WALLAROO_CONTROL_PORT}"
export WALLAROO_ARG_DATA="${WALLAROO_INIT_HOST}:${WALLAROO_DATA_PORT}"
export WALLAROO_ARG_EXTERNAL="${WALLAROO_INIT_HOST}:${WALLAROO_EXTERNAL_PORT}"
export WALLAROO_ARG_MY_CONTROL="__WORKER_HOST__:${WALLAROO_MY_CONTROL_PORT}"
export WALLAROO_ARG_MY_DATA="__WORKER_HOST__:${WALLAROO_MY_DATA_PORT}"
export WALLAROO_ARG_RESILIENCE="--run-with-resilience"
export WALLAROO_ARG_PONY="--ponynoblock --ponythreads=1 --ponyminthreads=9999"

export WALLAROO_BASE_ARGS="--in $WALLAROO_ARG_IN --out $WALLAROO_ARG_OUT --metrics $WALLAROO_ARG_METRICS --control $WALLAROO_ARG_CONTROL --external $WALLAROO_ARG_EXTERNAL $WALLAROO_ARG_RESILIENCE"

