#!/bin/sh

sudo rm /tmp/market-spread-*.evlog
sudo rm /tmp/market-spread-*.local-topology
sudo rm /tmp/market-spread-*.tcp-control
sudo rm /tmp/market-spread-*.tcp-data
sudo rm /tmp/market-spread-*.workers
