#!/bin/bash

export PYTHONPATH="../../machida:."

../../machida/build/machida --application-module word_count --in 127.0.0.1:7010 \
  --out 127.0.0.1:7002 --metrics 127.0.0.1:5001 \
  --control 127.0.0.1:6000 --data 127.0.0.1:6001 --external 127.0.0.1:6010 \
  --cluster-initializer --ponythreads=1
