#!/bin/bash

export PYTHONPATH="../../machida/lib:."

../../machida/build/machida --application-module word_count \
  --in 'Split and Count'@127.0.0.1:7012 \
  --out 127.0.0.1:7002 --metrics 127.0.0.1:5001 \
  --join 127.0.0.1:6000 --name worker3 \
  --my-control 127.0.0.1:13303 --my-data 127.0.0.1:13403 \
  --ponythreads=1 --ponypinasio --ponynoblock
