#!/bin/sh

if [[ -z $1 ]]; then
	echo 'You must provide an app name'
	exit 1
fi

docker run --rm -it -u `id -u` -v /home/ubuntu/wallaroo:/home/ubuntu/wallaroo -v ~/.gitconfig:/.gitconfig -w /home/ubuntu/wallaroo/apps/$1 --entrypoint stable sendence/ponyc:sendence-8.0.0-debug fetch

docker run --rm -it -u `id -u` -v /home/ubuntu/wallaroo:/home/ubuntu/wallaroo -w /home/ubuntu/wallaroo/apps/$1 --entrypoint stable sendence/ponyc:sendence-8.0.0-debug env ponyc  .
