#!/usr/bin/env python3

import click
from summarize import (two_file_line_iter,
                       parse_giles_line,
                       Summarizer,
                       FixedBins, Log10Bins)


@click.command()
@click.option('--sent', '-s', nargs=1, required=True, type=str,
              help='Path of the giles sent file')
@click.option('--recd', '-r', nargs=1, required=True, type=str,
              help='Path of the giles received file')
@click.option('--bin-type', '-b', type=click.Choice(['FixedBins', 'Log10Bins']),
              default='Log10Bins')
def summarize(sent, recd, bin_type):
    """Summarize a pair of giles sent and received text logs into a source-sink
    metrics summary."""
    if bin_type == 'FixedBins':
        bins = FixedBins
    else:
        bins = Log10Bins
    s = Summarizer(bins)
    for ls, lr in two_file_line_iter(sent, recd):
        ts0, _ = parse_giles_line(ls)
        ts1, _ = parse_giles_line(lr)
        s.count(ts0, ts1)
    print("Giles Report Summary")
    print("====================")
    print()
    print(s)


if __name__ == '__main__':
    summarize()
