#!/usr/bin/env python
import threading
import sys
import wallaroo.experimental
from kafka import KafkaProducer

connector = wallaroo.experimental.SinkConnector(required_params=['topic'], optional_params=['bootstrap_brokers'])
connector.listen()
bootstrap_brokers = connector.params.bootstrap_brokers or '127.0.0.1:9092'
producer = KafkaProducer(bootstrap_servers=bootstrap_brokers)

topic = connector.params.topic

while True:
    key, value = connector.read()
    producer.send(topic, key=str(key).encode('utf-8'),
                  value=str(value).encode('utf-8'))
