#!/usr/bin/env python
import sys
import wallaroo.experimental
from kafka import KafkaConsumer

connector = wallaroo.experimental.SourceConnector(required_params=['topics'], optional_params=['bootstrap_brokers', 'consumer_group'])
connector.connect()
bootstrap_brokers = connector.params.bootstrap_brokers or '127.0.0.1:9092'
consumer_group = connector.params.consumer_group or 'wallaroo'
consumer = KafkaConsumer(connector.params.topics, bootstrap_servers=bootstrap_brokers, group_id=consumer_group)

for message in consumer:
    extension.write(message.value)
