#!/usr/bin/env python
import sys
import time
import wallaroo.experimental
import boto3

connector = wallaroo.experimental.SourceConnector(required_params=['shard', 'stream'], optional_params=[])
connector.connect()

stream = connector.params.stream
shard_id = connector.params.shard
conn = boto3.client('kinesis')
shard_it = conn.get_shard_iterator(
    StreamName=stream, ShardId=shard_id, ShardIteratorType="LATEST")["ShardIterator"]

while True:
    message = conn.get_records(ShardIterator=shard_it, Limit=2)
    for record in message["Records"]:
        connector.write(record["Data"])
    shard_it = message["NextShardIterator"]
    time.sleep(0.2)
