#!/usr/bin/env python
import sys
import threading
import wallaroo.experimental
import boto3

connector = wallaroo.experimental.SinkConnector(required_params=['stream'], optional_params=[])
connector.listen()
stream = connector.params.stream
producer = boto3.client('kinesis')

while True:
    key, value = connector.read()
    producer.put_record(StreamName=stream, PartitionKey=key, Data=value)
