#!/usr/bin/env python
import sys
import wallaroo.experimental
from redis import Redis

connector = wallaroo.experimental.SourceConnector(required_params=['topic'], optional_params=['host', 'port', 'password'])
connector.connect()
redis = Redis(connector.params.host, int(connector.params.port), connector.params.password)

pubsub = redis.pubsub()
pubsub.subscribe(connector.params.topic)
for message in pubsub.listen():
    if message['type'] == 'message':
        connector.write(message['data'])