#!/usr/bin/env python
import sys
import wallaroo.experimental

if sys.version_info.major == 2:
    import SocketServer
else:
    import socketserver as SocketServer

class UDPHandler(SocketServer.BaseRequestHandler):
    def handle(self):
        data = self.request[0].strip()
        connector.write(data)

connector = wallaroo.experimental.SourceConnector(required_params=['host', 'port'], optional_params=[])
connector.connect()
params = connector.params
print("listening on host: " + params.host + " port: " + str(params.port))
server = SocketServer.UDPServer((params.host, int(params.port)), UDPHandler)
server.serve_forever()
