#!/bin/bash

./word_count_with_api --in 127.0.0.1:7010 --out 127.0.0.1:7002 \
  --metrics 127.0.0.1:5001 --control 127.0.0.1:6000 --data 127.0.0.1:6001 \
  --name worker1 --external 127.0.0.1:5050 --cluster-initializer \
  --ponynoblock --cluster-initializer
