#!/bin/sh

if [[ -z $1 ]]; then
	echo "USAGE ./clean directory"
	exit 0
fi

sudo rm $1/market-spread-*.evlog
sudo rm $1/market-spread-*.local-topology
sudo rm $1/market-spread-*.tcp-control
sudo rm $1/market-spread-*.tcp-data
sudo rm $1/market-spread-*.workers
