#!/usr/bin/env python3

import asyncore
import asynchat
import random
import socket
import struct
import sys
import traceback

from wallaroo.experimental import connector_wire_messages as cwm

class AsyncServer(asynchat.async_chat, object):
    def __init__(self, dispatcher, handler_id, sock, streams=None, name=None, source_map={}):
        print("AsyncServer.__init__", handler_id, sock)
        self._dispatcher = dispatcher
        self.name = name
        self.source_map = source_map
        self._id = handler_id
        self._conn = sock
        asynchat.async_chat.__init__(self, sock=self._conn)
        self.in_buffer = []
        self.out_buffer = []
        self.reading_header = True
        self.set_terminator(4) # first frame header
        self.in_handshake = True
        self._streams = {} if streams is None else streams
        self.received_count = 0
        self._reset_count = {}

    def collect_incoming_data(self, data):
        """Buffer the data"""
        self.in_buffer.append(data)

    def found_terminator(self):
        """Data is going to be in two parts:
        1. a 32-bit unsigned integer length header
        2. a payload of the size specified by (1)
        """
        if self.reading_header:
            # Read the header and set the terminator size for the payload
            self.reading_header = False
            h = struct.unpack(">I", b"".join(self.in_buffer))[0]
            self.in_buffer = []
            self.set_terminator(h)
        else:
            # Read the payload and pass it to _handle_frame
            frame_data = b"".join(self.in_buffer)
            self.in_buffer = []
            self.set_terminator(4) # read next frame header
            self.reading_header = True
            self._handle_frame(frame_data)

    def _handle_frame(self, frame):
        self.received_count += 1
        self.updated_received_count()
        msg = cwm.Frame.decode(frame)
        # Hello, Ok, Error, Notify, NotifyAck, Message, Ack, Restart
        self.count = 0
        if isinstance(msg, cwm.Hello):
            # respond with an ok or an error
            ok = cwm.Ok(200, self._streams.values(), self.source_map.items())
            self.write(ok)
        elif isinstance(msg, cwm.Notify):
            # respond with notifyack
            try:
                por = self._streams[msg.stream_id][2]
            except:
                por = 0
            notify_ack = cwm.NotifyAck(
                True,
                msg.stream_id,
                por)
            self._streams[msg.stream_id] = [msg.stream_id,
                                            msg.stream_name,
                                            por]
            self.write(notify_ack)
        elif isinstance(msg, cwm.Message):
            # no response, just print
            self.handle_message(msg)
        elif isinstance(msg, cwm.Error):
            # Got error message from worker
            # close the connection and pass msg to the error handler
            print("Received an error message. closing the connection")
            self.close()
            raise Exception(msg.message)
        else:
            # write the original message back
            self.write(msg)

    def handle_message(self, msg):
        # send an ack every 100 messages
        print("{} received message: {}".format(self.name, msg))
        if msg.message_id:
            self._streams[msg.stream_id][2] = msg.message_id
        if msg.flags & cwm.Message.Eos:
            # ack eos
            print("NH: acking eos for {}".format(msg))
            self.write(cwm.Ack(credits = 1,
                               acks= [(msg.stream_id, self._streams[msg.stream_id][2])]))

    def write(self, msg):
        print("{} write {}".format(self.name, msg))
        data = cwm.Frame.encode(msg)
        super(AsyncServer, self).push(data)

    def updated_received_count(self):
        if self.received_count % 200 == 0:
            # but reset point_of_ref back to 0 every 500
            # ... yes this will cause the sender to run forever.
            print("{} Sending ack for streams!".format(self.name))
            ack = cwm.Ack(
                credits = 200,
                acks = [
                    (sid, por) for sid, _, por in self._streams.values()])
            self.write(ack)
        if self.received_count == 500:
            # migrate!
            self.migrate()
        elif self.received_count % 1000 == 0:
            # send a restart every 1000 messages
            self.write(cwm.Restart())

    def handle_error(self):
        _type, _value, _traceback = sys.exc_info()
        traceback.print_exception(_type, _value, _traceback)

    def migrate(self):
        print("Migrating from {}".format(self.name))
        # remove self from source map
        del self.source_map[self.name]
        print("Remaining sources: {}".format(self.source_map))
        # craft update sources msg
        msg = cwm.UpdateSources(self.source_map.items())
        self.write(msg)
        self.write(cwm.Restart())
        self.close()
        self._dispatcher.close()

    def close(self):
        print("Closing the connection")
        print("last received id by stream:\n\t{}".format(
            "\n\t".join("{}, {}: {}".format(sid, sn, mid)
                      for sid, sn, mid in self._streams.values())))
        super(AsyncServer, self).close()
        self.socket.close()


class EchoServer(asyncore.dispatcher):

    def __init__(self, name, host, port, source_map={}, state={}):
        asyncore.dispatcher.__init__(self)
        self.create_socket(family=socket.AF_INET, type=socket.SOCK_STREAM)
        self.set_reuse_addr()
        self.bind((host, port))
        self.listen(1)
        self.name = name
        self.source_map = source_map
        self.source_map[self.name] = "{}:{}".format(host, port)
        self.count = 0
        self._streams = state

    def handle_accepted(self, sock, addr):
        print('Incoming connection from %s' % repr(addr))
        handler = AsyncServer(self, self.count, sock, self._streams, self.name, self.source_map)
        self.count += 1


state = {}
sources = {}
server1 = EchoServer('server1', '127.0.0.1', 7100, sources, state)
server2 = EchoServer('server2', '127.0.0.1', 7101, sources, state)
print("server1: ", server1)
print("server2: ", server2)
asyncore.loop(timeout=0.000001)
