CC=clang++
PONYC=ponyc

SDIR=cpp
IDIR=hpp
ODIR=build

CFLAGS=-Wall -std=c++11 -stdlib=libc++ -I$(IDIR)

_DEPS=market-spread-cpp.hpp
DEPS=$(patsubst %,$(IDIR)/%,$(_DEPS))

_OBJ=market-spread-cpp.o
OBJ=$(patsubst %,$(ODIR)/%,$(_OBJ))

LIBMS=$(ODIR)/libms.a
MSAPP=$(ODIR)/market-spread

AR=ar
ARFLAGS=rs

all: $(MSAPP)

lib: $(LIBCOUNTER)

$(ODIR)/%.o: $(SDIR)/%.cpp $(DEPS)
	$(CC) --debug -c -o $@ $< $(CFLAGS)

$(LIBMS): $(OBJ)
	$(AR) $(ARFLAGS) $@ $^

$(MSAPP): $(LIBMS) market-spread-cpp/market-spread-cpp.pony
	$(PONYC) --debug --export --output=$(ODIR) --path=../../../../lib:../../../../lib/wallaroo/cpp_api/cpp/cppapi/build/build/lib:./build market-spread-cpp

.PHONY: clean

clean:
	rm -rf $(ODIR)/*.o $(ODIR)/*.a $(ODIR)/market-spread-cpp*
